window.BADMINTON_VIDEOS = [
  {
    id: "5EYQIpDHl2Q",
    title: "Anders Antonsen vs Kunlavut Vitidsarn",
    tournament: "TOYOTA Thailand Open 2026 | Men's Singles Final",
    source: "BWF TV",
    published: "2026-05-17",
    priority: "final",
  },
  {
    id: "M_RXEVZqmp0",
    title: "Akane Yamaguchi vs Chen Yu Fei",
    tournament: "TOYOTA Thailand Open 2026 | Women's Singles Final",
    source: "BWF TV",
    published: "2026-05-17",
    priority: "final",
  },
  {
    id: "8ySsffkw7DA",
    title: "Rankireddy/Shetty vs Carnando/Marthin",
    tournament: "TOYOTA Thailand Open 2026 | Men's Doubles Final",
    source: "BWF TV",
    published: "2026-05-17",
    priority: "final",
  },
  {
    id: "fEMAA43QhHs",
    title: "Zhu/Li vs Christiansen/Boje",
    tournament: "TOYOTA Thailand Open 2026 | Mixed Doubles Final",
    source: "BWF TV",
    published: "2026-05-17",
    priority: "final",
  },
  {
    id: "rWjBVBZBeRc",
    title: "Iwanaga/Nakanishi vs Bao/Cao",
    tournament: "TOYOTA Thailand Open 2026 | Women's Doubles Final",
    source: "BWF TV",
    published: "2026-05-17",
    priority: "final",
  },
  {
    id: "BMkuuKqcun4",
    title: "Chou Tien Chen vs Kunlavut Vitidsarn",
    tournament: "TOYOTA Thailand Open 2026 | Men's Singles Semifinal",
    source: "BWF TV",
    published: "2026-05-16",
    priority: "semifinal",
  },
  {
    id: "4DfjRAbCN_8",
    title: "Akane Yamaguchi vs Pitchamon Opatniputh",
    tournament: "TOYOTA Thailand Open 2026 | Women's Singles Semifinal",
    source: "BWF TV",
    published: "2026-05-16",
    priority: "semifinal",
  },
  {
    id: "6EVLgKobZ6k",
    title: "Rankireddy/Shetty vs Goh/Izzuddin",
    tournament: "TOYOTA Thailand Open 2026 | Men's Doubles Semifinal",
    source: "BWF TV",
    published: "2026-05-16",
    priority: "semifinal",
  },
  {
    id: "KibpH-zcuE8",
    title: "Puavaranukroh/Paewsampran vs Zhu/Li",
    tournament: "TOYOTA Thailand Open 2026 | Mixed Doubles Semifinal",
    source: "BWF TV",
    published: "2026-05-16",
    priority: "semifinal",
  },
  {
    id: "J3JJNeH2x1Q",
    title: "Court 1 | Qualification/Round of 32",
    tournament: "PERODUA Malaysia Masters 2026 | Day 1",
    source: "BWF TV",
    published: "2026-05-18",
    priority: "latest-court",
  },
  {
    id: "8VbX3vb7KB4",
    title: "Court 2 | Qualification/Round of 32",
    tournament: "PERODUA Malaysia Masters 2026 | Day 1",
    source: "BWF TV",
    published: "2026-05-18",
    priority: "latest-court",
  },
  {
    id: "idU1FH5skJ4",
    title: "Court 3 | Qualification/Round of 32",
    tournament: "PERODUA Malaysia Masters 2026 | Day 1",
    source: "BWF TV",
    published: "2026-05-18",
    priority: "latest-court",
  },
  {
    id: "7_r5PTObCZw",
    title: "Court 4 | Qualification/Round of 32",
    tournament: "PERODUA Malaysia Masters 2026 | Day 1",
    source: "BWF TV",
    published: "2026-05-18",
    priority: "latest-court",
  },
];
